### ISSUE TITLE
Sample settings file is missing keys

### ISSUE THREAD

**Issue by primetheus** [github/saml-ldap-team-sync#15]
Using the sample config produces the following error:

```
Traceback (most recent call last):
  File "SAMLTeamSyncAD.py", line 195, in <module>
    main()
  File "SAMLTeamSyncAD.py", line 100, in main
    adsync = ADSync(settings_file)
  File "SAMLTeamSyncAD.py", line 25, in __init__
    self.AD_PAGE_SIZE = settings['ldap']['page_size']
KeyError: 'page_size'
```

### Solution

Add the following to the `settings.yml` file:

```
ldap:
  page_size: 1000
```

**Comment by primetheus** [comment]
Added in #17
