### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff

### ISSUE THREAD

**Issue by primetheus** [github/saml-ldap-team-sync#16]
Reading the YAML file fails with a `utf-8` error:

```
Traceback (most recent call last):
  File "SAMLTeamSyncAD.py", line 195, in <module>
    main()
  File "SAMLTeamSyncAD.py", line 100, in main
    adsync = ADSync(settings_file)
  File "SAMLTeamSyncAD.py", line 12, in __init__
    settings = yaml.load(stream, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/local/lib/python3.6/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

### Solution
To fix this, change `with open(settings_file, 'r') as stream:` to `with open(settings_file, 'rb') as stream:` so it reads as `bytes`

**Comment by primetheus** [comment]
Fixed in #17
